[tool.ruff]
line-length = 88
respect-gitignore = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "ANN201",  # Отсутствует аннотация типа возвращаемого значения для публичной функции
    "ANN003",  # Отсутствует аннотация типа для **kwargs
    "COM812",  # Отсутствует завершающая запятая
    "CPY",     # Связанные с авторским правом
    "D100",    # Отсутствует docstring в публичном модуле
    "D102",    # Отсутствует docstring в публичном методе
    "D103",    # Отсутствует docstring в публичной функции
    "D104",    # Отсутствует docstring в публичном пакете
    "D107",    # Отсутствует docstring в __init__
    "D203",    # 1 пустая строка перед docstring класса (конфликтует с D211)
    "D205",    # Требуется 1 пустая строка между кратким описанием и подробным
    "D213",    # Многострочный docstring должен начинаться со второй строки (конфликтует с D212)
    "DOC201",  # Docstring содержит секцию return, но функция ничего не возвращает
    "DOC501",  # В docstring отсутствуют исключения в секции Raises
    "DOC502",  # Описание исключения в docstring должно начинаться с заглавной буквы
    "DTZ001",  # Использование `datetime.datetime()` без аргумента `tzinfo` не разрешено
    "ERA001",  # Найден закомментированный код
    "FA102",   # Отсутствует `from __future__ import annotations`
    "RET502",  # Не возвращайте None неявно в функции, которая может вернуть не-None значение
    "RUF001",  # Строка содержит неоднозначный unicode символ
    "RUF002",  # Docstring содержит неоднозначный unicode символ
    "RUF003",  # Комментарий содержит неоднозначный unicode символ
]